name: PHP CS Fixer

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run PHP CS Fixer
        run: php vendor/bin/php-cs-fixer fix --verbose --diff --dry-run
