name: PHPStan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0' # Change to your desired PHP version

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    - name: Run PHPStan
      run: composer phpstan

    - name: Upload PHPStan results
      uses: actions/upload-artifact@v2
      with:
        name: phpstan-results
        path: phpstan-report.txt
