name: Inspections

on: 
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run PHPCS inspection
        uses: rtCamp/action-phpcs-code-review@v3
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          SKIP_FOLDERS: "tests,.github"
          PHPCS_SNIFFS_EXCLUDE: "WordPress.Files.FileName"
        with:
          args: "WordPress,WordPress-Core,WordPress-Docs"

      - name: AI Code Reviewer
        uses: theronakpatel/ai-code-reviewer@main
        with:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
